### ISSUE TITLE
env limitation

### ISSUE THREAD

**Issue by igor-ivanov** [Mellanox/ci-demo#23]
It seems that `env` is processed after `matrix`
As a result following yaml does not work as expected

```
matrix:
  axes:
    flags:
      - default
      - extra
    arch:
      - x86_64

env:
   TARGET: ${flags}

steps:
...
```

so workaround is required as:
```
matrix:
  axes:
    flags:
      - default
      - extra
    arch:
      - x86_64

steps:
  -name: N1
    run: export TARGET=${flags}
...
```
