### ISSUE TITLE
Wrong category 'tool' processing

### ISSUE THREAD

**Issue by igor-ivanov** [Mellanox/ci-demo#26]
README.md
```
# category:tools has special meaning - it will run for steps, that explicitly request it in the
# step`s containerSelector key.
```
but 

```
  - name: Service
    containerSelector:
      - "{variant:1}"
    agentSelector:
      - "{variant:1}"
    run: |
       echo SERVICE
...
  - name: Black Duck
    containerSelector: "{category:'tool', name: 'blackduck', variant:1}"
    enable: false
    shell: action
    module: ngci
    run: NGCIBlackDuckScan
```

launch `Service` step too on `blackduck` node

See:
http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/LIBVMA-PRO/detail/LIBVMA-PRO/106/pipeline/1835/

**Comment by igor-ivanov** [comment]
Is it planned to be resolved? it brakes effective usage.

**Comment by mike-dubman** [comment]
yep, bug:

here tool is scheduled to be skipped
https://github.com/Mellanox/ci-demo/blob/master/src/com/mellanox/cicd/Matrix.groovy#L439

but here - it can be re-elected
https://github.com/Mellanox/ci-demo/blob/master/src/com/mellanox/cicd/Matrix.groovy#L448

testing fix

**Comment by mike-dubman** [comment]
```agentSelector``` can operate only by ```nodeLabel```

**Comment by mike-dubman** [comment]
the behaviour is correct. for tools container - step should have explicit selector which picks what passes or what not.
you can try to specify ```category:  ''``` to filter out tools.

**Comment by mike-dubman** [comment]
or you can add any custom tag to container definition and pick only containers with tag: doit

**Comment by igor-ivanov** [comment]
> the behaviour is correct. for tools container - step should have explicit selector which picks what passes or what not.
> you can try to specify `category: ''` to filter out tools.

It does not work for me.  Service step is not run at all.
```
  - name: Service
    containerSelector:
      - "{category:'', variant:1}"
    agentSelector:
      - "{category:'', variant:1}"
```

**Comment by igor-ivanov** [comment]
> or you can add any custom tag to container definition and pick only containers with tag: doit

It is problematic to do for containers with predefined tags as
```
  - {name: 'rhel8.3-mofed-x86_64', url: 'harbor.mellanox.com/hpcx/x86_64/rhel8.3/builder:mofed-5.2-0.5.3.0', arch: 'x86_64'}
  - {name: 'sl15sp2-mofed-x86_64', url: 'harbor.mellanox.com/swx-infra/x86_64/sles15sp2/builder:mofed-5.2-2.2.0.0', arch: 'x86_64'}
  - {name: 'fc31-mofed-x86_64',    url: 'harbor.mellanox.com/swx-infra/x86_64/fedora31/builder:mofed-5.1-1.0.7.0', arch: 'x86_64'}
...
```

**Comment by igor-ivanov** [comment]
So, I still do not see obvious way to launch `Service` step for all containers and bare-metal nodes in variant 1 excluding containers having `category:'tool'`.
It stops me from enabling ci based on ci-demo

**Comment by igor-ivanov** [comment]
It seems that only way to get needed is
```
   - name: Service
     containerSelector:
      - "{name: 'rhel8.3-mofed-x86_64', variant:1}"
      - "{name: 'sl15sp2-mofed-x86_64', variant:1}"
      - "{name: 'fc31-mofed-x86_64', variant:1}"
      - "{name: 'ub20.04-mofed-x86_64', variant:1}"
      - "{name: 'rhel8.3-inbox-x86_64', variant:1}"
      - "{name: 'rhel8.3-inbox-aarch64', variant:1}"
      - "{name: 'rhel7.6-mofed-x86_64', variant:1}"
      - "{name: 'rhel7.6-inbox-x86_64', variant:1}"
     agentSelector:
      - "{nodeLabel: 'r-aa-zorro014', variant:1}"
```
It does not look friendly and requires updating readme.
