### ISSUE TITLE
Add 'enable' property for step

### ISSUE THREAD

**Issue by igor-ivanov** [Mellanox/ci-demo#30]
Feature request:
Add `enable=true|false` property for step as done for Blackduck.
It allows to configure steps from proj_jjb.yaml and skip one if `enable=false`

It looks as adding additional condition into if (see https://github.com/Mellanox/ci-demo/blob/7ab23a01997387cac9c38fc76251f1a5341721c5/src/com/mellanox/cicd/Matrix.groovy#L542) should be enough.

**Comment by igor-ivanov** [comment]
Question:

should following constuction diasable step Blackduck from execution?

proj_jjb.yaml
```
        - bool:
            name: "do_blackduck"
            default: false
            description: "Run BlackDuck."
```

matrix_job.yaml
```
  - name: Blackduck
    enable: ${do_blackduck}
```

**Comment by mike-dubman** [comment]
yes, it should work.
please let know

**Comment by igor-ivanov** [comment]
I do not see expected result
```
        - bool:
            name: "do_artifact"
            default: true
            description: "Collect artifacts."
```

```
  - name: Artifacts
    enable: ${do_artifact}
    run: |
      if [ -d jenkins ]; then
        gzip -f ./jenkins/*.tar 2>/dev/null || true
        cd ./jenkins/ ;
          for f in *.tar.gz ; do [ -e "$f" ] && mv "$f" "${flags}/arch-${name}-$f" ; done ;
        cd ..
        cd ./jenkins/${flags};
          for f in *.tap ; do [ -e "$f" ] && mv "$f" "${flags}-${name}-$f" ; done ;
        cd ../..
      fi
    parallel: false
    archiveArtifacts: |
      jenkins/**/arch-*.tar.gz
    archiveTap: |
      jenkins/**/*.tap
```

![image](https://user-images.githubusercontent.com/9037172/113982223-2b3b1f80-9851-11eb-8ac1-82dd2007e298.png)

but

Artifacts step is executed
![image](https://user-images.githubusercontent.com/9037172/113982386-5cb3eb00-9851-11eb-89b4-4e796cb43758.png)
